site_name: SpyHunt
site_description: Fast, clean SpyHunt Python package
site_url: https://spyhunt.readthedocs.io
repo_url: https://github.com/Pymmdrza/SpyHunt


nav:
  - Home: index.md
  - Install: '#installation'
  - Basic Usage: '#basic-usage'
  - Performance: '#performance-benefits'
  - Development: '#-development'
  - Quality: '#code-quality'
  - Support: '#-support'
  - Owner: 'https://mmdrza.com'

theme:
  name: readthedocs
  locale: en
  collapse_by_default: false
  include_homepage_in_sidebar: true
  features:
    - navigation.tabs
    - navigation.instant

plugins:
  - search:
      indexing: 'full'

markdown_extensions:
  - smarty
  - toc:
      permalink: true
      separator: "-"
  - sane_lists
